Traceback (most recent call last):
  File "/var/spool/slurm/job14129515/slurm_script", line 68, in <module>
    main(get_args())
  File "/var/spool/slurm/job14129515/slurm_script", line 41, in main
    A, nmap = get_adjacency(args.network_file)
  File "/var/spool/slurm/job14129515/slurm_script", line 24, in get_adjacency
    df    = pd.read_csv(filename, delim_whitespace = True, header = None)
  File "/cluster/tufts/cowenlab/.envs/denoise/lib/python3.7/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/cluster/tufts/cowenlab/.envs/denoise/lib/python3.7/site-packages/pandas/io/parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/cluster/tufts/cowenlab/.envs/denoise/lib/python3.7/site-packages/pandas/io/parsers.py", line 946, in __init__
    self._make_engine(self.engine)
  File "/cluster/tufts/cowenlab/.envs/denoise/lib/python3.7/site-packages/pandas/io/parsers.py", line 1178, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/cluster/tufts/cowenlab/.envs/denoise/lib/python3.7/site-packages/pandas/io/parsers.py", line 2008, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: ''
